apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: sietch-buildbase
  name: sietch-buildbase
spec:
  source:
    dockerfile: |-
      FROM node:lts-alpine
      # needed to run node-gyp for some modules
      RUN apk add --no-cache git make gcc g++ python pkgconfig pixman-dev cairo-dev pango-dev libjpeg-turbo-dev giflib-dev
      WORKDIR /app
      ENV NODE_ENV production
  strategy:
    type: Docker
    dockerStrategy:
  output:
    to:
      kind: ImageStreamTag
      name: sietch-buildbase:latest
  triggers:
  - type: ConfigChange
  - imageChange:
      type: ImageChange