kind: Template
apiVersion: v1
metadata:
  name: my-buildConfig-sietch-build-template
objects:
  # The image stream that this build will create
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      generation: 1
      name: sietch-build
      spec:
        lookupPolicy:
        local: false

  # The build in question.

  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      labels:
        app: sietch-build-${RELEASE_BRANCH}
        component: appimage
      name: sietch-build-${RELEASE_BRANCH}
    spec:
      source:
        type: Git
        git:
          uri: https://github.com/nathanieltagg/sietch.git
          ref: ${RELEASE_BRANCH}
        dockerfile: |-
          FROM scratch
          RUN chown node:node /app
          USER node
          ENV NODE_ENV production
          WORKDIR /app
          COPY package*.json /app/
          RUN ls -al
          RUN npm ci --only=production
          RUN ls -al

      strategy:
        type: Docker
        dockerStrategy:
          from: 
            kind: ImageStreamTag
            name: sietch-buildbase:latest
          contextDir: ./
      output:
        to:
          kind: ImageStreamTag
          name: sietch-build:${RELEASE_BRANCH}
      triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChange: {}
      - type: "GitHub"
        github:
          secret: "${GITHUB_SECRET}"

parameters:
  - name: GITHUB_SECRET
    displayName: The "secret" given to the github webjook
    require: true
  - name: RELEASE_BRANCH
    displayName: Which branch of the github directory I'm building from.
    value: master
    require: true
message: "HI there"
